{{- if and .Values.restic.restServer.auth.enabled (not .Values.restic.restServer.auth.secretName) }}
{{- $password := include "restic-rest-server.defaultPassword" . }}
{{- $username := .Values.restic.restServer.auth.username }}
{{- $htpasswd := (printf "%v:%v\n" .Values.restic.restServer.auth.username (bcrypt $password) ) | b64enc -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (include "restic-rest-server.usersSecret" .)) }}
{{- if $secret }}
{{- $htpasswd = get $secret.data .Values.restic.restServer.auth.htpasswdKey }}
{{- end }}
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: {{ include "restic-rest-server.usersSecret" . }}
  labels: {{ include "restic-rest-server.labels" . | nindent 4 }}
data:
  # Plain: {{ $password }}
  {{ .Values.restic.restServer.auth.htpasswdKey }}: {{ $htpasswd | quote }}
{{- end }}
